Update tag.yml

diff --git a/.github/workflows/tag.yml b/.github/workflows/tag.yml
--- a/.github/workflows/tag.yml
+++ b/.github/workflows/tag.yml
@@ -9,29 +9,26 @@ jobs:
     steps:
     - uses: actions/checkout@v2
 
-    # Set up your project environment, for example, Python
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.8'
 
-    # Install pylint
     - name: Install pylint
       run: pip install pylint
 
-    # Run pylint and handle the output
     - name: Run Linter
       id: lint
       run: |
-        pylint_output=$(pylint . --output-format=text)
+        pylint_output=$(pylint . --output-format=text) || true
         echo "$pylint_output"
         lint_score=$(echo "$pylint_output" | grep "Your code has been rated at" | sed 's/.*rated at \([-0-9.]*\)\/.*/\1/')
         echo "LINT_SCORE=$lint_score" >> $GITHUB_ENV
-        if [[ "$lint_score" != "" && $(echo "$lint_score < 7" | bc) -eq 1 ]]; then
+        if [ -z "$lint_score" ] || [[ $(echo "$lint_score < 7" | bc) -eq 1 ]]; then
+          echo "Lint score too low or not found"
           exit 1
         fi
 
-    # Conditional step to check the lint score and create a tag
     - name: Create Tag
       if: ${{ github.ref == 'refs/heads/master' }}
       run: |
@@ -45,7 +42,7 @@ jobs:
       if: ${{ github.ref != 'refs/heads/master' }}
       run: |
         BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')
-        SNAPSHOT_TAG=v$(date +'%Y%m%d%H%M%S')-SNAPSHOT
+        SNAPSHOT_TAG="${BRANCH_NAME}-v$(date +'%Y%m%d%H%M%S')-SNAPSHOT"
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git tag $SNAPSHOT_TAG
